apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-succeeds
spec:
  template:
    spec:
      containers:
      - name: main
        image: busybox
        command:
        - "sh"
        - "-c"
        - "echo 'Sleepin a bit...' && sleep 5 && echo 'Hmm coffee is ready!' && exit 0"
      # Do not restart a failed container.
      restartPolicy: Never
  # Try 0x to restart the Pod if needed (e.g. if a Node fails).
  backoffLimit: 0
